server:
  port: 9935
spring:
  banner:
    location: classpath:apacheKafkaBanner.txt
  kafka:
    producer:
      bootstrap-servers:
      - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
